### ISSUE TITLE
Error on run python3.6

### ISSUE THREAD

**Issue by pochubayk** [sid5432/pyOTDR#4] opened 2017-12-05 09:18 UTC
Traceback (most recent call last):
  File "pyOTDR.py", line 7, in <module>
    import read
  File "/home/www/read.py", line 6, in <module>
    from . import parts
ImportError: attempted relative import with no known parent package

**Comment by sid5432** [comment] 2017-12-06 01:08
I can't reproduce the exact error you are seeing (with python 3.6.3), but it may be related to the file organization.   Your traceback shows "/home/www/read.py"; all the files should be under the folder pyOTDR.  It looks like you have all the files under /home/www instead?

**Comment by pochubayk** [comment] 2017-12-06 09:23
@sid5432 I was able to get it working have you had any luck taking the data and displaying a graph?

**Comment by sid5432** [comment] 2017-12-06 13:28
I'm a bit confused: this is just a simple program designed to spit out a tab delimited data file (two columns), with the file name like demo_ab-trace.dat.  Plotting and displaying the data is up to you, with the help of some other plotting program (you can even use Excel, if that is your cup of tea).  Are you running this using the Docker container?  The set up as it is right now with the Docker build and execution dumps the trace file *inside* the container, which goes away afterwards, so you'll never see the trace file.  I am modifying that, but haven't committed the code to Github  yet.

**Closed as completed** 2017-12-07 22:10 UTC
