### ISSUE TITLE
unable to install pyOTDR packge 

### ISSUE THREAD

**Issue by sowmendran** [sid5432/pyOTDR#29] opened 2020-06-19 08:29 UTC
When I try installing pyOTDR module (using pip install pyOTDR)  in python3.6 it gives following error,
ERROR: Command errored out with exit status 1:  command: 'C:\Users\sowmendranp\Desktop\PythonLearn\SOR_Learn\venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sowmendranp\\AppData\\Local\\Temp\\pycharm-packaging\\lazyxml\\setup.py'"'"';__file__='"'"'C:\\Users\\sowmendranp\\AppData\\Local\\Temp\\pycharm-packaging\\lazyxml\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\SOWMEN~1\AppData\Local\Temp\pip-pip-egg-info-wkphl4iv'
cwd: C:\Users\sowmendranp\AppData\Local\Temp\pycharm-packaging\lazyxml\ Complete output (9 lines):
Traceback (most recent call last):
 File "<string>", line 1, in <module>
 File "C:\Users\sowmendranp\AppData\Local\Temp\pycharm-packaging\lazyxml\setup.py", line 16, in <module> import lazyxml
    File "C:\Users\sowmendranp\AppData\Local\Temp\pycharm-packaging\lazyxml\lazyxml\__init__.py", line 15, in <module>
        from . import builder
      File "C:\Users\sowmendranp\AppData\Local\Temp\pycharm-packaging\lazyxml\lazyxml\builder.py", line 7, in <module>
        import utils
    ModuleNotFoundError: No module named 'utils'
    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 

But I could download and install pyOTDR package in python2.7, unfortunately I am not able to run it, while attempt to run i  get following error,

(venv) C:\Users\sowmendranp\Desktop\PythonLearn\SOR2\venv\Scripts>pyOTDR.exe otdr.sor
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\sowmendranp\Desktop\PythonLearn\SOR2\venv\Scripts\pyOTDR.exe\__main__.py", line 4, in <module>
  File "c:\users\sowmendranp\desktop\pythonlearn\sor2\venv\lib\site-packages\pyOTDR\__init__.py", line 12, in <module>
    from .read import sorparse
  File "c:\users\sowmendranp\desktop\pythonlearn\sor2\venv\lib\site-packages\pyOTDR\read.py", line 10, in <module>
    from . import fxdparams
  File "c:\users\sowmendranp\desktop\pythonlearn\sor2\venv\lib\site-packages\pyOTDR\fxdparams.py", line 4, in <module>
    from datetime import datetime, timezone
ImportError: cannot import name timezone

While trying to figure out about the error, I learned that timezone is not supported in python2.7

If someone could help me with your suggestion to install and use pyOTDR module in python,  it will be of great help to me.

**Comment by OSHI7** [comment] 2020-06-19 13:25
I had trouble installing the lazyxml library.
Can you confirm that installed?

**Comment by sid5432** [comment] 2020-06-20 00:38
There is a messy dependency issue that might be the cause. The module "utils" needs to be installed first. The lazyxml module has some issues resolving this (which is why Remi has been working to move away from lazyxml). Try installing "utils" first and see if that solves the problem.

**Comment by sowmendran** [comment] 2020-06-23 06:33
> There is a messy dependency issue that might be the cause. The module "utils" needs to be installed first. The lazyxml module has some issues resolving this (which is why Remi has been working to move away from lazyxml). Try installing "utils" first and see if that solves the problem.

I tried installing utils and lazyxml package before installing pyOTDR, 
utils package installation was successful, but lazyxml installtion fails with below error,
 ollecting lazyxml
  Using cached https://files.pythonhosted.org/packages/eb/ca/9fe2223845fb0e6637a99fe485fc3535e471b12e4a016332c9cabf0264a6/lazyxml-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sowmendranp\AppData\Local\Temp\pycharm-packaging\lazyxml\setup.py", line 20, in <module>
        readme = fp.read()
      File "C:\Users\sowmendranp\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 399: character maps to <undefined>
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\sowmendranp\AppData\Local\Temp\pycharm-packaging\lazyxml\

**Comment by RemiDesgrange** [comment] 2020-06-23 07:41
It seems to be more of an issue with lazyxml than with pyOTDR. 

You can install the version from git through pip, but py2 is not supported anymore in master branch.


```
pip install git+https://github.com/sid5432/pyOTDR@master
```

I'm currently working on a refactoring of pyOTDR (some ideas [here](https://github.com/RemiDesgrange/pyotdr-next) That's why I did not release v1.1.0 (or v2) which will be py3 only and without lazyxml

**Comment by sbcp** [comment] 2020-12-24 15:10
I had trouble installing the lazyxml library,too
The lazyxml only support python2.7?
------------------
pip-install-0mgsptli\lazyxml_61d402ba98d34a08af61cfac682bd975\setup.py", line 20, in <module>
        readme = fp.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 397: illegal multibyte sequence
    ----------------------------------------

**Comment by sbcp** [comment] 2020-12-24 15:13
> ## I had trouble installing the lazyxml library,too
> The lazyxml only support python2.7?
> pip-install-0mgsptli\lazyxml_61d402ba98d34a08af61cfac682bd975\setup.py", line 20, in
> readme = fp.read()
> UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 397: illegal multibyte sequence
> ----------------------------------------

lazyxml/docs/changelog.rst
1.3.0 (2019-12-09)
Bug fix and refactor.
Only support Python 2.7.

**Comment by sbcp** [comment] 2020-12-24 15:25
> > ## I had trouble installing the lazyxml library,too
> > ## The lazyxml only support python2.7?
> > pip-install-0mgsptli\lazyxml_61d402ba98d34a08af61cfac682bd975\setup.py", line 20, in
> > readme = fp.read()
> > UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 397: illegal multibyte sequence
> 
> lazyxml/docs/changelog.rst
> 1.3.0 (2019-12-09)
> Bug fix and refactor.
> Only support Python 2.7.

GET IT!!!
Don't use "pip install pyotdr",use setup.py

**Comment by sid5432** [comment] 2020-12-25 03:35
lazyxml has been a problem for a while, but we just haven't gotten around to fixing it yet. Sorry guys! On Linux it does still work in Python 3 (at least it works with 3.9.1 and 3.8.5) ; the trick is that you really need to "pip install utils" first before trying to install lazyxml (installing them at the same time just doesn't work). I don't use Windows very much nowadays, so I don't really know.

**Comment by RemiDesgrange** [comment] 2021-06-10 12:35
Python 2 is deprecated and new version of pyotdr only supports python 3, I'm closing this.

**Closed as completed by RemiDesgrange** 2021-06-10 12:35 UTC
